### ISSUE TITLE
parse daily readings from source

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/get-catholic-daily-readings#4]
# Summary
From the page downloaded from the USCCB, parse the content to obtain a clean formatted selection of daily readings.

# Tasks
- [x] Get daily header (eg. "Monday of the Thirtieth Week in Ordinary Time")
- [x] Get Lectionary number
- [x] Get ALL readings (even if more or less than 3)
- [x] Reading should include Reading header
- [x] Reading should include Bible reference
- [x] Reading should include text
- [x] Text should be included (a) raw, (b) non-formatted (raw text without original html formatting), and formatted (original html formatting converted to JS formatting)
