### ISSUE TITLE
create API

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/get-catholic-daily-readings#8]
# Summary
Provide a REST API for others to use, instead of the NPM package.

# Tasks
- [ ] Dockerize
- [ ] Setup cloud project
- [ ] Setup CICD to deploy to cloud
- [ ] Setup automatic cost limits so I don't pay too much for the API
